### PR TITLE
CodeBuild Reporting

### PR DESCRIPTION
**Pull request by duganth-va**
US Gov West 1 recently received reporting support for CodeBuild. This PR just show cases that to see if it's something that the team would be interested in. 

[Report](https://console.amazonaws-us-gov.com/codesuite/codebuild/008577686731/testReports/reportGroups/oauth-proxy-ci-junit-reports?region=us-gov-west-1&reports-meta=eyJmIjp7InRleHQiOiIifSwicyI6eyJwcm9wZXJ0eSI6InN0YXR1cyJ9LCJuIjoyMCwiaSI6MH0)

image

image

### CODE REVIEW

**Review by beaugrantham-va — CHANGES_REQUESTED** [review]
Looks like some permissions/roles are needed.

**Comment by duganth-va** [comment]
Yeah I do need to do some IAM changes, but was interested on your thoughts of using the reporting feature prior to changing IAM roles etc. One question though, does the report link work for you?

**Comment by beaugrantham-va** [comment]
> Yeah I do need to do some IAM changes, but was interested on your thoughts of using the reporting feature prior to changing IAM roles etc. One question though, does the report link work for you?

I think it's a great addition. The report link works for me.

**Comment by beaugrantham-va** [comment]
Closing for now, until this is ready to be dusted off.

**Pull request closed without merging**
