### PR TITLE
API-2338-update-formation-dependency Updated formation from 3.0.0 to …

### PR DESCRIPTION
**Pull request by bdgrider**
…6.9.5

Updated the dependency @department-of-veterans-affairs/formation from 3.0.0 to 6.9.5. 

https://vajira.max.gov/browse/API-2338

### CODE REVIEW

**Comment by beaugrantham-va** [comment]
Were there any UI/styling changes as a result of this since the dependency affects CSS?

**Comment by crolarlibertyva** [comment]
> Were there any UI/styling changes as a result of this since the dependency affects CSS?

Change seems good so far. When i did a run, I didn't notice any changes in the rendering of the saml-proxy page. I'll try again and look more closely though.

**Review by crolarlibertyva — APPROVED** [review]
Looks good to me. Authenticates correctly in my local setup.

**Comment by bdgrider** [comment]
Would that just be the authentication page accessible via localhost:7000? @beaugrantham-va It appears to be unchanged.

**Comment by bdgrider** [comment]
I just verified nothing on the auth page appears different or broken.

**Comment by bdgrider** [comment]
The CSS appears unchanged but the auth flow is not working as it should. I am getting this matching error after entering what I believe to be correct log in information @beaugrantham-va 

image

**Comment by bdgrider** [comment]
After regression testing the saml-proxy after updating this dependency, there appeared to be no style changes that occurred. All functionality was exercised and is in working order.

**Review by lukemarkwordtlibertyits — APPROVED** [review]
My tests passed. Looks good to me.

**Pull request merged**
