### PR TITLE
Api 2418 oauth proxy update node fetch

### PR DESCRIPTION
**Pull request by lukemarkwordtlibertyits**
[API2418_Tests.docx](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5258537/API2418_Tests.docx)

### CODE REVIEW

**Review by crolarlibertyva — COMMENTED** [review]
@lukemarkwordtlibertyits : Do we know if there's an updated docker image to reference in the Dockerfile?

**Comment by crolarlibertyva** [comment]
> @lukemarkwordtlibertyits : Do we know if there's an updated docker image to reference in the Dockerfile?

Nevermind. It's already set to the latest tag.

**Review by crolarlibertyva — COMMENTED** [review]
Runs good for me.

**Review by dbrown-va — APPROVED** [review]
Confirmed both the initial OAuth flow and ability to obtain a refresh token, so functionally I think this is good to go.

Avoiding npm force resolutions would be preferable from a maintenance perspective, so let's hold on the merge until we sync up.

**Comment by beaugrantham-va** [comment]
Closing pending parent dependency updates and/or action with developer-portal-backend.

**Pull request closed without merging**
