### PR TITLE
Fix styles

### PR DESCRIPTION
**Pull request by kalilsn**
Resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/560

- Centers content at all viewport widths
- Decreases page margins to 18px
- Increases button heights to 50px
- Adjusts placement of help text on small screens

I also made the header size static because it seemed to get unnecessarily small between 1100 and 640px. Happy to revert that if it's an issue.

### CODE REVIEW

**Comment by juliaelman** [comment]
Great job @kalilsn. A few notes:

- Make the button height back to the original height on larger screen
- ID.me create account button should be full width
- The text in the buttons should be vertically centered, see screenshot below
- Make all the buttons full width to the page, relative to the padding around the page

Please feel free to post screenshots in the comments of this issue. Don't worry about adding too many too! Great for folks to see how this progresses. 😄 

screen shot 2018-11-13 at 2 13 24 pm

**Comment by kalilsn** [comment]
@juliaelman Updated in response to your feedback. Here's screenshots at a few different widths, but let me know if you need more info!

screen shot 2018-11-13 at 2 29 14 pm
screen shot 2018-11-13 at 2 29 00 pm
screen shot 2018-11-13 at 2 28 54 pm

**Comment by juliaelman** [comment]
@kalilsn nice! One last thing, can we make the VA logo a bit smaller on mobile view? I think it was before, so maybe reset to that original size.

**Comment by kalilsn** [comment]
@juliaelman I went ahead and made it responsive again because I don't remember why I changed that in the first place.

screen shot 2018-11-13 at 3 39 47 pm

screen shot 2018-11-13 at 3 39 59 pm

screen shot 2018-11-13 at 3 40 13 pm

**Pull request merged**
