### PR TITLE
Api 4620 basic account behavior fix

### PR DESCRIPTION
**Pull request by crolarlibertyva**
- Uses query parameter to get relay state
- More unit tests

### CODE REVIEW

**Comment by bdgrider-va** [comment]
I am getting error messages that seem to pertain to relay state when manually exercising this locally. Could be an issue on my end with config, thought.

image

**Review by bdgrider-va — DISMISSED** [review]
All linting and unit tests pass. There appears to be an issue with how the authnRequest/relay state is being handled, though.

**Comment by crolarlibertyva** [comment]
> I am getting error messages that seem to pertain to relay state when manually exercising this locally. Could be an issue on my end with config, though.
> 
> image
> 
> image
> 
> ^ The above is referencing the relayStateQuery, which was undefined, on line 27 of utils.js.

Pushed another change. Had the grab in the wrong spot.

**Review by bdgrider-va — APPROVED** [review]
Verified unit tests, normal auth flow with test user 001, and verified before and after basic MHV user behavior (master shows error page, this branch redirects to verify page).

**Pull request merged**
