### PR TITLE
API-2338-font-404-fix Fixing font 404's by updating route in express …

### PR DESCRIPTION
**Pull request by bdgrider**
Fixing font 404's by adding a new route in the express middleware so that requests looking for fonts at samlproxy/assets/fonts will be directed to the public/fonts directory.

### CODE REVIEW

**Comment by beaugrantham-va** [comment]
There are many references to `font/`... how are these affected?

```
$ grep -ir "[\"|/]fonts/" * | grep -v "bootstrap" | wc -l
14
```

**Comment by beaugrantham-va** [comment]
How are these references to `fonts/` affected?

```
$ grep -ir "[\"|/]fonts/" * | grep -v "bootstrap"
styles/core.scss:    src: url("fonts/fa-solid-900.woff2") format("woff2"),
styles/core.scss:         url("fonts/fa-solid-900.woff") format("woff"),
styles/core.scss:         url("fonts/fa-solid-900.eot") format("eot");
```

**Comment by bdgrider** [comment]
I just updated the PR to include the old /fonts route so as not to break anything that depends on it.

**Comment by beaugrantham-va** [comment]
This branch is pending some additional edits.

**Pull request closed without merging**
